### ISSUE TITLE
Suggestions are not applied

### ISSUE THREAD

**Issue by clojj** [hoovercj/vscode-haskell-linter#6] opened 2015-12-21 09:25 UTC
Accepting the suggestion does not replace/apply here (Mac OSX, latest VSCode 0.10.5)

![vscode-haskell-linter](https://cloud.githubusercontent.com/assets/4367963/11927479/1550417a-a7cd-11e5-9d9d-40c862d9d57f.png)

Clicking on the 'accept...' link after opening the light-bulb does nothing.

**Comment by hoovercj** [comment] 2015-12-21 10:16
Thanks for confirming this. I began investigating #4 yesterday and noticed that NO suggestions were being accepted and thought I must have messed something up locally. Now I'm wondering if the latest VS Code update has broken something.

**Comment by clojj** [comment] 2015-12-21 21:18
Trying to debug your extension with VSCode... I can't stop at any breakpoints after launching the extension via F5

Building it is Ok
It even signales diagnostics in the launched VSCode instance.... but all breakpoints seem to be ingored.

Strange

**Comment by clojj** [comment] 2015-12-21 22:03
Weird: debugging your extension gives this message inside the debugger:
"TypeError: document.getText is not a function"
(renamed the var to 'toText')

![debugging](https://cloud.githubusercontent.com/assets/4367963/11942467/11f7bcd2-a837-11e5-9ef4-b041eb23bbf0.png)

Looking into the VSCode API, TextDocument stil has this method though:
getText(range?: Range): string

**Comment by hoovercj** [comment] 2015-12-21 23:12
Thanks for following up, I noticed that as well. `provideCodeActions` (at the top of your screenshot) is an interface method that gets called by Code. It's job is to return a list of commands and any arguments they need, and the command will be triggered when a user selects an action from the lightbulb. The command calls `runCodeAction`. I'm passing along the document object, which worked in the previous version of Code, but appears not to be working now (though I don't have immediate access to a previous version of Code to confirm this).

I am doing this because it seemed like the cleanest way to have access to the text document when performing the action. Do you know of a better way? I need it because if the user is only linting on save rather than on typing, the same action could be applied twice which caused weird effects, so I have a guard in place which makes sure the hlint suggestion still matches the text in question. It is admittedly not the prettiest solution, but the extension was hacked together in an afternoon.

I'm hoping https://github.com/Microsoft/vscode-docs/issues/93 is quickly addressed so I can double check the regression on my own and provide more evidence to open an issue on the Code repository if necessary.

**Comment by clojj** [comment] 2015-12-22 22:42
I wish there would be more documentation available about it... tried many different ways to replace the range in runCodeAction(), but VSCode won't update it, no matter what API-function I call.

Guess there's something fundamentally different in the latest version(s)

Maybe the go-language extension, which I assume is the 'most curated' language-extension out there, can show us how this is supposed to be done ..?

**Comment by hoovercj** [comment] 2015-12-23 02:03
Exactly. The issue is that I haven't really found many extensions that use code actions. I'm playing around with a new haskell extension for ghc-mod in the meantime, but hopefully I'll also get this resolved over the holidays.

Thanks for your interest in the extension.

**Comment by hoovercj** [comment] 2015-12-30 10:12
This was caused by https://github.com/Microsoft/vscode/issues/1698 and is fixed now.

**Closed as completed** 2015-12-30 10:13 UTC

**Comment by clojj** [comment] 2015-12-30 22:22
Great!
works here
